on: push
name: Check-On-New-Leads
jobs: 
  slackNotification:
    name: Check On New Leads
    runs-on: ubuntu-latest
    steps:
    - name: Get current skip value      
      run: |
        skip=$(curl https://xnap1.onrender.com/getskipcount)
        echo "skip value: $skip" 
        echo "$skip" > skip.txt  
    - name: Curl request
      run: |
        skip=$(cat skip.txt)
        echo "skip value: $skip"
        curl "https://xnap1.onrender.com/findemails?next=5&skip=$skip"
    - uses: actions/checkout@v2
    - name: Slack Notify
      uses: rtCamp/action-slack-notify@v2.2.0
      env:        
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_MESSAGE: "Email Search Alert skip value is: $(<skip.txt>) :rocket:"
        SLACK_TITLE: Email Search Alert
        SLACK_USERNAME: MonitorLeads
