on: push
name: Check-On-New-Leads
jobs: 
  slackNotification:
    name: Check On New Leads
    runs-on: ubuntu-latest
    steps:
    - name: Get current skip value
      id: get_current_skip_value
      run: |
        skip=$(curl https://xnap1.onrender.com/getskipcount)
        echo "skip value: $skip"   
    - name: Curl request
      run: |
        echo "skip value: $skip"
        curl "https://xnap1.onrender.com/findemails?next=5&skip=${{ steps.get_current_skip_value.outputs.skip }}"
    - uses: actions/checkout@v2
    - name: Slack Notify
      uses: rtCamp/action-slack-notify@v2.2.0
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_MESSAGE: ${{ env.skip }} ":rocket:"
        SLACK_TITLE: Email Search Alert
        SLACK_USERNAME: MonitorLeads
