
on:
  schedule:
    - cron:  '2 * * * *'    # At every 2 minutes
name: Check-On-New-Leads
jobs: 
  slackNotification:
    name: Check On New Leads
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notify
      uses: rtCamp/action-slack-notify@v2.2.0
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_MESSAGE: 'Test Post Content :rocket:'
        SLACK_TITLE: Lead Alert
        SLACK_USERNAME: MonitorLeads
