on:
  push:
    branches:
    - main    
jobs:
  my_job:
    name: deploy to staging
    runs-on: ubuntu-18.04
    steps:
      - name: Notify slack
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: pullreminders/slack-action@master
        with:
          args: '{\"channel\":\"C1234567890\",\"text\":\"Hello world\"}'
