on:
  schedule:
    - cron:  '0 * * * *'

jobs:
  monitor-api:
    runs-on: ubuntu-latest
    steps:
    - name: Send request to API endpoint
      run: |
        curl -s https://xnap1.onrender.com/" | grep "expected response"
    - name: Check response
      run: |
        if [ $? -ne 0 ]; then
          echo "Unexpected response from API endpoint"
          exit 1
        fi
    - name: Send notification
      if: failure()
      uses: https://hooks.slack.com/services/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
      with:
        to: 'dioscarr@gmail.com'
        subject: 'API endpoint failed'
        message: 'The response from the API endpoint did not match the expected response.'
