on:
  schedule:
    - cron:  '0 * * * *'
jobs:
  monitor-api:
    runs-on: ubuntu-latest
    steps:
    - name: Send request to API endpoint
      run: |
        curl -s https://xnap1.onrender.com/leads" | grep "expected response"
    - name: Check response
      run: |
        if [ $? -ne 0 ]; then
          echo "Unexpected response from API endpoint"
          exit 1
        fi
    - name: Send notification
      if: failure()
      uses: slack-actions/slack@v1
      with:
        args: 'send --webhook-url https://hooks.slack.com/services/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 --message "API endpoint failed"'
